export const ENDPOINT = {
  SEND_OTP: "/api/auth/sendOrResend-otp",
  VERIFY_OTP: "/api/auth/verify-otp",
  GET_PRODUCT_INFO: "/api/products",
  CREATE_ADDRESS: "/api/addresses",
  GET_ADDRESS: "/api/addresses",
  ADD_TO_CART: "/api/cart",
  MERGE_CART: "/api/cart/merge",
  CREATE_ORDER: "/api/orders",
  UPDATE_ADDRESS: "/api/addresses",
  LOGOUT: "/api/auth/logout",
  ADD_REVIEW: "/api/products",
  GET_REVIEWS: "/api/products",
  UPLOAD_IMAGE: "/api/storage/upload",
  FETCH_PINCODE: "/api/pincode",
  CREATE_PAYMENT_ORDER: "/api/payments/paymentOrder",
  CHECK_ORDER_STATUS: "/api/payments/checkOrderStatus",
  GET_ORDER_BY_ID: "/api/orders",
};
